### PR TITLE
Added routes and controllers for courses, created collections for cou…

### PR DESCRIPTION
**Pull request by dvardcr**
Added routes and controllers for courses, created collections for courses and students and updated the routes.rest file with students and courses

### CODE REVIEW

**Comment by vicentemferrer** [comment]
It seems good! I think you may provide a review for my incoming PR to discuss some changes that may affect in this PR merge.

**Comment by vicentemferrer** [comment]
PR for Error handling is open! #4

**Review by vicentemferrer — COMMENTED** [review]
It looks good

**Review by benjaminjalebeau — COMMENTED** [review]
Looks good, I didn't go too in depth so that I can merge it for vicente to start his stuff.

**Pull request merged**
