### PR TITLE
Error Handling and First Validation Approach

### PR DESCRIPTION
**Pull request by vicentemferrer**
### Files created
- utilities/
  -  errors.js - _Contains error variant classes and handle errors functions_
  -  teachers-validation.js - _Contains validation rules and middleware for create (POST) and update (PUT) routes_
  - id-validation.js - _Contains validation rules and middleware for GET by id and DELETE routes (**Note: they are in their own file because they may work for equivalent routes in other collections**)_

### Files changed
- server.js
    
    **Description**
    Express Error Handler implemented.

- data/
  - database.js 
    
    **Description**
    ```javascript
    const getDatabase = () => {
	if (!database) {
	  throw Error('Database not initialized');
	}
	return database.db('students'); // Added .db(...) method in return to access the DB at once
    };
    ``` 
    **Note: this change may affect current PR openned by Benjamin, so the inclusion of this change is open to your opinions**

- routes/
  - teachers.js
    
    **Description**
    Implementation of validation and error handling in routes. Rewritten **Promise** approach to **try/catch** approach.

- controllers/
  - teachers.js
    
    **Description**
    Rewritten **Promise** approach to **try/catch** approach. Use of custom errors for error handling.

  - student.js
    
    **Description**
    Added custom errors. No major changes performed. Waiting for changes.

### CODE REVIEW

**Comment by vicentemferrer** [comment]
### Project Settings changed
- Resaved **swagger-autogen**, and **dotenv** as development libraries. Render.com already works with environment variables loaded, so dotenv is just to work in our local machines.

### Files changed
- swagger.json
  
  **Description**
  Teachers routes documentation was enriched. **Note: It's better writing documentation than use _swagger-autogen_ (when handleErrors(...) is implemented, it breaks library workflow)**

### Files deleted
- utilities/
  - index.js
  - validation.js

**Comment by dvardcr** [comment]
Thank you for all the updates applied, adding the error handler and validation to teachers. Should I add the Students' validation?

**Comment by vicentemferrer** [comment]
No, I'll implement validation and error handling once our PR are merged.

**Review by benjaminjalebeau — COMMENTED** [review]
As far as I can tell, it looks good. For the sake of time I'm not going to test everything so that  this can be merged.

**Pull request merged**
